### ISSUE TITLE
Wrong link for "Vazir Code"

### ISSUE THREAD

**Issue by PAPIONbit** [rastikerdar/rastikerdar.github.io#4]
سلام
ظاهرا به دلیل Replace همه نام ها آدرس لینک وزیر کد هم به اشتباه جایگزین شده:
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa#:~:text=Vazir%20Code%20WOL%20(%D9%81%D9%88%D9%86%D8%AA%20Vazirmatn%20Code%20%D8%A8%D8%AF%D9%88%D9%86%20%D8%AD%D8%B1%D9%88%D9%81%20%D9%84%D8%A7%D8%AA%DB%8C%D9%86)
![image](https://user-images.githubusercontent.com/47592258/157668550-b35d256e-0b02-4e0c-817d-667b416c3f31.png)
و لینک که به جای
https://github.com/rastikerdar/vazir-code-font
به
https://github.com/rastikerdar/vazirmatn-code-font
آدرس دهی شده.

**Comment by rastikerdar** [comment]
سلام
ممنونم برای ایشو. مشکل اکنون برطرف شد. البته مخزن وزیرمتن به همراه وبسایتش در این آدرس است:
https://github.com/rastikerdar/vazirmatn
با تشکر
